### ISSUE TITLE
Fix font size

### ISSUE THREAD

**Issue by galulex** [activebridge/activebridge#126]
Some text is smaller. `web development` for instance
![](https://cloud.githubusercontent.com/assets/483482/22193616/42b4525c-e145-11e6-82ed-eaa74ed5aeb6.png)

**Comment by abscondite** [comment]
Cannot reproduce
![photo_2017-02-20_14-20-32](https://cloud.githubusercontent.com/assets/8594891/23124889/ea2e918a-f777-11e6-86d5-a16a12a94c63.jpg)
![photo_2017-02-20_14-20-39](https://cloud.githubusercontent.com/assets/8594891/23124890/ea49d10c-f777-11e6-8bb2-69bb98506edd.jpg)
![photo_2017-02-20_14-20-53](https://cloud.githubusercontent.com/assets/8594891/23124891/ea53bb4a-f777-11e6-91b8-2d00d464e2fd.jpg)
I think we need to test it using @galulex ~~Chinese brick~~ android phone
