### ISSUE TITLE
Background improvement

### ISSUE THREAD

**Issue by qqumn** [activebridge/activebridge#148]
Just try to use grey-black gradient instead of violet color
<img width="712" alt="2017-02-14 20 38 29" src="https://cloud.githubusercontent.com/assets/12530189/22943285/afc4d54e-f2f5-11e6-87ae-0ca6b1b64154.png">

**Comment by abscondite** [comment]
I have changed background for root page. Should I change it for others? (About, projects, testimonials, team, services?)

**Comment by galulex** [comment]
@qqumn ?

**Comment by qqumn** [comment]
@abscondite I think we will do it in future. If you change bg for other pages, you have to change all colors for bg patterns and colored `div` blocks.
