### ISSUE TITLE
Testimonials for mobile

### ISSUE THREAD

**Issue by galulex** [activebridge/activebridge#162]
Implement testimonials screen for mobile.

@qqumn Could you provide some design mobile mockup for that?

**Comment by qqumn** [comment]
Da da da, capitan! @galulex

**Comment by qqumn** [comment]
<img width="446" alt="2017-03-14 13 02 53" src="https://cloud.githubusercontent.com/assets/12530189/23897671/b3d69498-08b6-11e7-9f1d-98e385ebd5cd.png">
