### ISSUE TITLE
Envelope responsive

### ISSUE THREAD

**Issue by qqumn** [activebridge/activebridge#229]
Fix responsive sizes. On 1366x768 main branch (master) looks good, but on my laptop (2560 x 1600 retina) it's not so well.
![image](https://cloud.githubusercontent.com/assets/12530189/24827025/c5a9b21a-1c4b-11e7-99de-e0a902bb4dcb.png)

We've to change width and height dimension on form elements, submit button and contact info.

Check it on most usable screen sizes and on mozilla firefox.

**Comment by galulex** [comment]
![](https://s3.amazonaws.com/upload.screenshot.co/fdc66226e4)

**Comment by qqumn** [comment]
I think, it's a good idea to redesign small "send request" envelop and it's animation. We'll remove old one.

**Comment by galulex** [comment]
@qqumn arrow keys does not work anymore

**Comment by qqumn** [comment]
@galulex I'm checking these functionality right now. Hm, all works well.
You have to make camera focused to use arrow navigation.
