### ISSUE TITLE
Full HD display bug (Chrome)

### ISSUE THREAD

**Issue by daryakuritsyna** [activebridge/activebridge#239]
![Responsive Design](http://storage8.static.itmages.com/i/17/0418/h_1492516961_4304734_fd297e03d3.png)

**Comment by qqumn** [comment]
@daryakuritsyna, we speak about this 1920×1080 resolution? 
![image](https://cloud.githubusercontent.com/assets/12530189/25130760/fb59bdb2-244b-11e7-9cef-74df4df61e24.png)
