### ISSUE TITLE
Change font for article

### ISSUE THREAD

**Issue by denqxotl** [activebridge/activebridge#253]
Very difficult to read articles. Make fonts little bit thinner and remove letter spacing
![2017-05-17 15 48 14](https://cloud.githubusercontent.com/assets/6824649/26154463/45910c40-3b18-11e7-91b5-eb8e54c2069f.png)

As for me, this text more readable than before

![2017-05-17 15 52 43](https://cloud.githubusercontent.com/assets/6824649/26154617/eab37640-3b18-11e7-92af-0221aa883b97.png)

**Comment by galulex** [comment]
https://github.com/activebridge/activebridge/issues/283
