### ISSUE TITLE
Blog design update

### ISSUE THREAD

**Issue by galulex** [activebridge/activebridge#283]

**Comment by Lena-ActiveBridge** [comment]
> 1. Треба шоб назви постів влазили повністю завжди.
> 2. Розділ "популярні пости" повинен бути згори лише коли вибрано "All posts". В інших випадках я б переносила вниз.
> 3. Стрілочки для гортання постів внизу я б теж зробила, бо зараз треба скролить нагору шоб натиснути "наступна сторінка".
> 4. Корпоративний шрифт у нас **Raleway**, як я наче вияснила (ним написане лого), тому ним пишемо заголовки та пункти меню. Самі пости робимо на світлому фоні темним шрифтом **Cera**, бо він охуєнний і добре читабельний))
[Stripe.zip](https://github.com/activebridge/activebridge/files/1457119/Stripe.zip)
[CERA.zip](https://github.com/activebridge/activebridge/files/1457122/CERA.zip)
[raleway.zip](https://github.com/activebridge/activebridge/files/1457127/raleway.zip)

Gradient color: #201030 (R: 32 G: 16 B:48)

![blog 1](https://user-images.githubusercontent.com/32668595/32599012-e660047c-c543-11e7-8c2e-10a979cd4d4c.jpg)
![post cera](https://user-images.githubusercontent.com/32668595/32599014-e6811360-c543-11e7-8ea9-c3d7f095f3d7.jpg)
