### ISSUE TITLE
Portfolio design update

### ISSUE THREAD

**Issue by galulex** [activebridge/activebridge#284]

**Comment by Lena-ActiveBridge** [comment]
![hexagon1](https://user-images.githubusercontent.com/32668595/32431659-0167129c-c2dd-11e7-8de4-8b928d2b4d9e.jpg)
![hexagon2](https://user-images.githubusercontent.com/32668595/32431660-0182bccc-c2dd-11e7-894b-92bf488cc4d8.jpg)
![hexagon3](https://user-images.githubusercontent.com/32668595/32431661-01a324f8-c2dd-11e7-825c-dccfdc4dcbe1.jpg)
